# ------------------------------------------------------------------------------
# MUL Project: FFmpeg GUI Blender Add-on
# Author:       Tomáš Klecer
# Date:         26.4.2026
# University:   Brno University of Technology
# Supervisor:   Ing. Tomáš Chlubna, Ph.D.
# Description:  Add-on entry point. Imports individual modules so theyregister their
#               classes with ClassManager and then does the actual
#               registration with Blender.
# Note:         Partially generated by Claude Opus 4.7
# ------------------------------------------------------------------------------
"""FFmpeg GUI add-on for Blender."""

bl_info = {
    "name": "FFmpeg GUI",
    "author": "Tomáš Klecer",
    "version": (1, 0, 0),
    "blender": (4, 5, 0),
    "location": "Properties > Output Properties > FFmpeg Encode",
    "description": "Graphical interface for FFmpeg encoding from Blender",
    "category": "Render",
}

import bpy

from .class_manager import ClassManager
from .log_service import LogService

_LOG = LogService.get_logger("init")

from . import properties
from . import preferences
from . import operators
from . import ui


def register():
    _LOG.info("Registering FFmpeg GUI add-on")
    ClassManager.register_all()

    bpy.types.Scene.mul_ffmpeg = bpy.props.PointerProperty(type=properties.MUL_FFmpegProps)

    ui.topbar_menu.register_menu()


def unregister():
    _LOG.info("Unregistering FFmpeg GUI add-on")

    ui.topbar_menu.unregister_menu()

    if hasattr(bpy.types.Scene, "mul_ffmpeg"):
        del bpy.types.Scene.mul_ffmpeg

    ClassManager.unregister_all()


if __name__ == "__main__":
    register()
