# ------------------------------------------------------------------------------
# MUL Project: FFmpeg GUI Blender Add-on
# Author:       Tomáš Klecer
# Date:         26.4.2026
# University:   Brno University of Technology
# Supervisor:   Ing. Tomáš Chlubna, Ph.D.
# Description:  Helper script driven by the Makefile. Packs the add-on into a
#               zip archive installable by Blender, cleans build artefacts and can copy
#               the unpacked add-on into the local Blender extensions folder.
# Note:         Partially generated by Claude Opus 4.7
# ------------------------------------------------------------------------------
"""Build helper for the FFmpeg GUI add-on."""

import os
import shutil
import sys
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))

EXCLUDE_DIR_NAMES = {"__pycache__", ".pytest_cache", ".mypy_cache", ".git"}
EXCLUDE_FILE_SUFFIX = (".pyc", ".pyo", ".tds", ".obj", ".lib", ".o")
EXCLUDE_FILE_NAMES = {os.path.basename(__file__), "Makefile"}


def _iter_addon_files():
    for root, dirs, files in os.walk(HERE):
        dirs[:] = sorted(d for d in dirs if d not in EXCLUDE_DIR_NAMES)
        for name in sorted(files):
            if name in EXCLUDE_FILE_NAMES:
                continue
            if name.endswith(EXCLUDE_FILE_SUFFIX):
                continue
            full = os.path.join(root, name)
            rel = os.path.relpath(full, HERE)
            yield full, rel


def build_zip(zip_name):
    out = os.path.join(os.path.dirname(HERE), zip_name)
    if os.path.exists(out):
        os.remove(out)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for full, rel in _iter_addon_files():
            if os.path.basename(full) == zip_name:
                continue
            zf.write(full, rel)
    print(f"Created {out}")


def clean(zip_name):
    for root, dirs, files in os.walk(HERE):
        for d in list(dirs):
            if d in EXCLUDE_DIR_NAMES:
                full = os.path.join(root, d)
                shutil.rmtree(full, ignore_errors=True)
                dirs.remove(d)
        for f in files:
            if f.endswith(EXCLUDE_FILE_SUFFIX):
                try:
                    os.remove(os.path.join(root, f))
                except OSError:
                    pass
    parent_zip = os.path.join(os.path.dirname(HERE), zip_name)
    if os.path.exists(parent_zip):
        os.remove(parent_zip)
        print(f"Removed {parent_zip}")


def install_local():
    """Copy the addon directory to the user's Blender 4.5 extensions folder."""
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if not appdata:
            print("Could not locate %APPDATA%", file=sys.stderr)
            return 1
        target_root = os.path.join(appdata, "Blender Foundation", "Blender", "4.5",
                                   "extensions", "user_default", "ffmpeg_blender_gui")
    elif sys.platform == "darwin":
        target_root = os.path.expanduser(
            "~/Library/Application Support/Blender/4.5/extensions/user_default/ffmpeg_blender_gui")
    else:
        target_root = os.path.expanduser(
            "~/.config/blender/4.5/extensions/user_default/ffmpeg_blender_gui")

    if os.path.isdir(target_root):
        shutil.rmtree(target_root)
    os.makedirs(target_root, exist_ok=True)

    for full, rel in _iter_addon_files():
        dst = os.path.join(target_root, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(full, dst)

    print(f"Installed to {target_root}")
    return 0


def main(argv):
    if "--clean" in argv:
        zip_name = next((a for a in argv if a.endswith(".zip")), "FFmpeg_Blender_GUI.zip")
        clean(zip_name)
        return 0
    if "--install" in argv:
        return install_local()

    zip_name = argv[1] if len(argv) > 1 else "FFmpeg_Blender_GUI.zip"
    build_zip(zip_name)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
