# ------------------------------------------------------------------------------
# MUL Project: FFmpeg GUI Blender Add-on
# Author:       Tomáš Klecer
# Date:         26.4.2026
# Description:  This is not a real Makefile, but rather set of build helpers..
# Note:         Partially generated by Claude Opus 4.7
#
# Targets:
#   make zip         Produce FFmpeg_Blender_GUI.zip (installable in Blender).
#   make clean       Remove __pycache__ and the produced zip.
#   make install     Copy the unpacked add-on into the users Blender extensions
#                    folder for quick local testing.
# ------------------------------------------------------------------------------

PYTHON ?= python
ZIP_NAME ?= FFmpeg_Blender_GUI.zip

.PHONY: zip clean install help

help:
	@echo "Available targets:"
	@echo "  zip       -- build $(ZIP_NAME) (Blender extension archive)"
	@echo "  clean     -- remove generated artefacts"
	@echo "  install   -- copy add-on to local Blender extensions folder"

zip: clean
	$(PYTHON) build_zip.py $(ZIP_NAME)

clean:
	$(PYTHON) build_zip.py --clean $(ZIP_NAME)

install:
	$(PYTHON) build_zip.py --install
