# ------------------------------------------------------------------------------
# MUL Project: FFmpeg GUI Blender Add-on
# Author:       Tomáš Klecer
# Date:         26.4.2026
# University:   Brno University of Technology
# Supervisor:   Ing. Tomáš Chlubna, Ph.D.
# Description:  Init for the operators package. Importing each module makes it
#               register its class with ClassManager.
# Note:         Partially generated by Claude Opus 4.7
# ------------------------------------------------------------------------------
"""Operators for the FFmpeg GUI add-on."""

from ..log_service import LogService

_LOG = LogService.get_logger("operators.init")

from .op_detect_ffmpeg import MUL_OT_DetectFFmpeg
from .op_test_ffmpeg import MUL_OT_TestFFmpeg
from .op_render_and_encode import MUL_OT_RenderAndEncode
from .op_encode_existing import MUL_OT_EncodeExisting
from .op_copy_command import MUL_OT_CopyCommand
from .op_show_settings import MUL_OT_ShowSettings

__all__ = [
    "MUL_OT_DetectFFmpeg",
    "MUL_OT_TestFFmpeg",
    "MUL_OT_RenderAndEncode",
    "MUL_OT_EncodeExisting",
    "MUL_OT_CopyCommand",
    "MUL_OT_ShowSettings",
]
