# ------------------------------------------------------------------------------
# MUL Project: FFmpeg GUI Blender Add-on
# Author:       Tomáš Klecer
# Date:         26.4.2026
# University:   Brno University of Technology
# Supervisor:   Ing. Tomáš Chlubna, Ph.D.
# Description:  Init for the UI package. Each panel module registers its class
#               with ClassManager on import.
# Note:         Partially generated by Claude Opus 4.7
# ------------------------------------------------------------------------------
"""UI package."""

from ..log_service import LogService

_LOG = LogService.get_logger("ui.init")

from .panel_main import MUL_PT_FFmpeg
from .panel_video import MUL_PT_FFmpeg_Video
from .panel_audio import MUL_PT_FFmpeg_Audio
from .panel_advanced import MUL_PT_FFmpeg_Advanced
from .panel_preview import MUL_PT_FFmpeg_Preview
from . import topbar_menu

__all__ = [
    "MUL_PT_FFmpeg",
    "MUL_PT_FFmpeg_Video",
    "MUL_PT_FFmpeg_Audio",
    "MUL_PT_FFmpeg_Advanced",
    "MUL_PT_FFmpeg_Preview",
    "topbar_menu",
]
